//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTW_QLBH_HUNMYI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CTHD_BAN = new HashSet<CTHD_BAN>();
            this.CHITIET_GIOHANG = new HashSet<CHITIET_GIOHANG>();
            this.CHITIETPHIEUNHAP = new HashSet<CHITIETPHIEUNHAP>();
        }
    
        public string MASP { get; set; }
        public string TENSP { get; set; }
        public string HINHANH { get; set; }
        public string MOTA { get; set; }
        public Nullable<int> SOLUONGTON { get; set; }
        public Nullable<decimal> GIA { get; set; }
        public string TRANGTHAI { get; set; }
        public string MADM { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD_BAN> CTHD_BAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_GIOHANG> CHITIET_GIOHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUNHAP> CHITIETPHIEUNHAP { get; set; }
        public virtual DANHMUC DANHMUC { get; set; }
    }
}
